# Generated by Django 4.1.4 on 2023-01-02 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movieapp.movie'),
        ),
    ]
