# Generated by Django 4.1.4 on 2023-01-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_rename_name_director_title_alter_review_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='title',
            new_name='name',
        ),
    ]
