# Generated by Django 4.1.4 on 2023-01-03 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_rename_title_director_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.name'),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.stars'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.coment'),
        ),
    ]
